# Just place this file in your repo under the .github/workflows folder. 

name: Deploy to Testflight

on:
 push:
    branches:
      - main
      - test
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if PR was merged
        if: github.event.pull_request.merged
        run: echo "PR was merged."

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YOUR_NPM_TOKEN }}

      - name: Setup Github Credentials
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email "gh-actions-${GITHUB_ACTOR}@github.com"

      - name: Bump Version Numbers
        run: npm run release
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YOUR_NPM_TOKEN }}

      - name: Push Changelog
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          tags: true

      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-username: "${{ secrets.YOUR_EXPO_USER }}"
          expo-password: "${{ secrets.YOUR_EXPO_PASSWORD }}"
          expo-cache: true

      - name: Build iOS App
        run: expo build:ios --non-interactive
        env:
          EXPO_APPLE_ID: ${{ secrets.YOUR_APPLE_ACCOUNT_ID }}
          EXPO_APPLE_PASSWORD: ${{ secrets.YOUR_APPLE_ACCOUNT_PASSWORD }}

      - name: Download Artifact from expo
        run: mkdir build_artifacts; export EXPO_ARTIFACT_URL=$(expo url:ipa); curl $EXPO_ARTIFACT_URL --output ./build_artifacts/$(basename $EXPO_ARTIFACT_URL);

      - name: Upload Artifact to Testflight
        run: xcrun altool --upload-app --type ios --file ./build_artifacts/$(basename $(expo url:ipa)) --username $APPLE_USER_NAME --password $APPLE_APP_SPECIFIC_PASSWORD
        env:
          APPLE_USER_NAME: ${{ secrets.YOUR_APPLE_ACCOUNT_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.YOUR_APP_SPECIFIC_PASSWORD }}
