name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g npm@latest
        
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install Expo CLI 
        run : npm install -g eas-cli
         
      - name: Set Expo account credentials
        run: |
          echo "EXPO_USERNAME=${{ secrets.YOUR_EXPO_USER }}" >> $GITHUB_ENV
          echo "EXPO_PASSWORD=${{ secrets.YOUR_EXPO_PASSWORD }}" >> $GITHUB_ENV

      #- name: Log in to Expo
        #run: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      #  run: expo login -u gusapc-inguz -p P5$$g60rd

      - name: Build IPA
        run: expo-cli build:ios

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: ./ios/build/*.ipa

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download IPA
        uses: actions/download-artifact@v2
        with:
          name: ipa
          path: ./ipa

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Set Apple account credentials
        run: |
          echo "EXPO_APPLE_USERNAME=${{ secrets.YOUR_APPLE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "EXPO_APPLE_PASSWORD=${{ secrets.YOUR_APPLE_ACCOUNT_PASSWORD }}" >> $GITHUB_ENV

  
