name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g npm@latest

      - name: instalarliberias
        run: npm uninstall wrench
             npm install fs-extra

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Expo CLI
        run: yarn add expo
        
      - name: Set Expo account credentials
        run: |
          echo "EXPO_USERNAME=${{ secrets.YOUR_EXPO_USER }}" >> $GITHUB_ENV
          echo "EXPO_PASSWORD=${{ secrets.YOUR_EXPO_PASSWORD }}" >> $GITHUB_ENV
      - name: Setup Expo
              #indica que este paso utiliza la acción expo-github-action en su versión 7. 
        uses: expo/expo-github-action@v7
              #especifica los parámetros que se pasarán a la acción expo-github-action.
        with:
                #indica que se debe configurar la última versión de Expo.
                expo-version: latest
                #indica que se debe configurar la última versión de eas.
                eas-version: latest
                #pasa el valor de la variable secreta EXPO_TOKEN como token para la acción.
                #Este token se utiliza para autenticarse con Expo.
                token: ${{ secrets.EXPO_TOKEN }}
      #- name: Log in to Expo
        #run: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      #  run: expo login -u gusapc-inguz -p P5$$g60rd

      - name: Build IPA
        run:  npm install -g eas-cli
              eas build -p ios 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: ./ios/build/*.ipa

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Buscar archivos IPA
        run: |
          find . -name "*.ipa"        
        shell: bash
      - name: Download IPA
        uses: actions/download-artifact@v2
        with:
          name: ipa
          path: ./ipa

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Set Apple account credentials
        run: |
          echo "EXPO_APPLE_USERNAME=${{ secrets.YOUR_APPLE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "EXPO_APPLE_PASSWORD=${{ secrets.YOUR_APPLE_ACCOUNT_PASSWORD }}" >> $GITHUB_ENV

  
